<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
        <DebugType>Embedded</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>false</IncludeSymbols>
        <IncludeSource>false</IncludeSource>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <IncludeReferencedProjects>true</IncludeReferencedProjects>
    </PropertyGroup>

    <PropertyGroup>
        <Company>G-MAN Solutions</Company>
        <Authors>Gabriel Palma</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Not.Again.NUnit</PackageId>
        <Description>Not Again API module for NUnit3</Description>
        <RepositoryUrl>https://github.com/gman-au/not-again</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Not.Again.Tests.Unit" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.7.0"/>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Not.Again.Infrastructure\Not.Again.Infrastructure.csproj"/>
    </ItemGroup>

    <!-- Include referenced project outputs -->
    <ItemGroup>
        <None Include="$(OutputPath)Not.Again.*.*.dll" Pack="true" PackagePath="lib\$(TargetFramework)"/>
        <None Include="$(OutputPath)Not.Again.*.dll" Pack="true" PackagePath="lib\$(TargetFramework)"/>
        <None Include="$(OutputPath)Not.Again.*.*.pdb" Pack="true" PackagePath="lib\$(TargetFramework)"/>
        <None Include="$(OutputPath)Not.Again.*.pdb" Pack="true" PackagePath="lib\$(TargetFramework)"/>
    </ItemGroup>

</Project>
