<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.33"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Not.Again.Domain\Not.Again.Domain.csproj"/>
        <ProjectReference Include="..\Not.Again.Enum\Not.Again.Enum.csproj" />
        <ProjectReference Include="..\Not.Again.Infrastructure\Not.Again.Infrastructure.csproj" />
        <ProjectReference Include="..\Not.Again.Interfaces\Not.Again.Interfaces.csproj"/>
    </ItemGroup>

</Project>
